### ISSUE TITLE
Rust client unable to establish grpc connectivity to event store on GKE

### ISSUE THREAD

**Issue by cloudgk** [EventStore/EventStore#3379]
**Describe the bug**
The eventstore DB is deployed in GKE public cluster and the service is exposed as nodeport over public ip. It is deployed using helm package https://artifacthub.io/packages/helm/eventstore/eventstore. And the values are default. The rust client is trying to connect with no ssl secure. 

**To Reproduce**
1. Install evenstore using HELM on GKE Cluster.
2. Use the rust client to connect to service 

**Expected behavior**
Rust client is able to connect to event store docker container and it should be able to connect to the GKE service as well.

**Actual behavior**
Failing to connect to service

**Config/Logs/Screenshots**
[2022-01-14T06:06:24Z DEBUG h2::codec::framed_write] send frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) } 
[2022-01-14T06:06:24Z DEBUG h2::codec::framed_write] send frame=Data { stream_id: StreamId(1) } 
[2022-01-14T06:06:24Z DEBUG h2::codec::framed_write] send frame=Data { stream_id: StreamId(1), flags: (0x1: END_STREAM) } 
[2022-01-14T06:06:24Z DEBUG h2::proto::connection] Connection::poll; connection error error=GoAway(b"", FRAME_SIZE_ERROR, Library) 
[2022-01-14T06:06:24Z DEBUG h2::codec::framed_write] send frame=GoAway { error_code: FRAME_SIZE_ERROR, last_stream_id: StreamId(0) } 
[2022-01-14T06:06:24Z DEBUG h2::proto::connection] Connection::poll; connection error error=GoAway(b"", FRAME_SIZE_ERROR, Library) 
[2022-01-14T06:06:24Z DEBUG hyper::client::service] connection error: hyper::Error(Http2, Error { kind: GoAway(b"", FRAME_SIZE_ERROR, Library) }) 
[2022-01-14T06:06:24Z DEBUG hyper::proto::h2::client] connection error: connection error detected: frame with invalid size 
[2022-01-14T06:06:24Z DEBUG hyper::proto::h2::client] client response error: connection error detected: frame with invalid size 
[2022-01-14T06:06:24Z DEBUG eventstore::grpc] Failed to retrieve gossip information from candidate Endpoint { host: "34.106.45.160", port: 32013 }: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
[2022-01-14T06:06:24Z WARN  eventstore::grpc] Unable to select a node. Retrying...(3/3)
[2022-01-14T06:06:24Z ERROR eventstore::grpc] Maximum discovery attempt count reached: 3
[2022-01-14T06:06:24Z DEBUG eventstore::grpc] Current msg: Msg::GetChannel, rest: [[]]
Error: GrpcConnectionError(MaxDiscoveryAttemptReached(3))

**EventStore details**
 - EventStore server version: 4.1.1.0

 - Operating system: client is running on Linux CentOS or Ubuntu (tried from both)

 - EventStore client version (if applicable):

**Additional context**

**Comment by YoEight** [comment]
Hey @cloudgk, by looking at the logs, you are using the gRPC Rust client on an unsupported server version. The Rust gRPC client is compatible with the 20.6 version and onward. 

Now, on crates.io there is a Rust TCP client that should work with your server version, even if the client itself was made when version 5 was out: https://crates.io/crates/eventstore/0.8.1

The dependencies version might be too old but I'm willing to update that version of the Rust TCP client if it can help you

**Comment by YoEight** [comment]
I might be biased but I recommend the 21.10.1 version :slightly_smiling_face:

**Comment by YoEight** [comment]
@cloudgk Also I recommend using the master branch of the Rust client as I will release version 2.0.0 very soon: https://github.com/EventStore/EventStoreDB-Client-Rust

**Comment by cloudgk** [comment]
Thank you for lightening fast response!! will install that right now using HELM and keep you posted.

**Comment by YoEight** [comment]
@cloudgk I released the `2.0.0-alpha.1` version in the meantime on Crates.io: https://crates.io/crates/eventstore/2.0.0-alpha.1

It's simpler that way.

**Comment by cloudgk** [comment]
@YoEight I am facing 

**CrashLoopBackOff** | eventstore/eventstore:21.10.1-buster-slim 

Have you faced this issue before with this image on K8's?

**Comment by YoEight** [comment]
We don't officially support K8s configuration but I know some managed to make it work. The best I can do here is to redirect you to the official documentation: https://developers.eventstore.com/server/v21.10/installation/linux.html#quick-start

Note that recent versions of ESDB uses gRPC and has TCP turned off by default. So you might have to revise your current K8s configuration entirely.

**Comment by cloudgk** [comment]
@YoEight After lot of tweaking and removing deprecated config parameters from helm chart, I have installed **Event Store 21.10.1.0**  on GKE.  Unable to connect to the eventstore with rust client, the same issue persists.

Below DEBUG info:

```
[2022-01-14T13:53:44Z DEBUG eventstore::grpc] Calling gossip endpoint on: Endpoint { host: "10.43.68.27", port: 31311 }
[2022-01-14T13:53:44Z DEBUG tower::buffer::worker] service.ready=true processing request 
[2022-01-14T13:53:44Z DEBUG h2::codec::framed_write] send frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) } 
[2022-01-14T13:53:44Z DEBUG h2::codec::framed_write] send frame=Data { stream_id: StreamId(1) } 
[2022-01-14T13:53:44Z DEBUG h2::codec::framed_write] send frame=Data { stream_id: StreamId(1), flags: (0x1: END_STREAM) } 
[2022-01-14T13:53:44Z DEBUG h2::proto::connection] Connection::poll; connection error error=GoAway(b"", FRAME_SIZE_ERROR, Library) 
[2022-01-14T13:53:44Z DEBUG h2::codec::framed_write] send frame=GoAway { error_code: FRAME_SIZE_ERROR, last_stream_id: StreamId(0) } 
[2022-01-14T13:53:44Z DEBUG h2::proto::connection] Connection::poll; connection error error=GoAway(b"", FRAME_SIZE_ERROR, Library) 
[2022-01-14T13:53:44Z DEBUG hyper::client::service] connection error: hyper::Error(Http2, Error { kind: GoAway(b"", FRAME_SIZE_ERROR, Library) }) 
[2022-01-14T13:53:44Z DEBUG hyper::proto::h2::client] connection error: connection error detected: frame with invalid size 
[2022-01-14T13:53:44Z DEBUG hyper::proto::h2::client] client response error: connection error detected: frame with invalid size 
[2022-01-14T13:53:44Z DEBUG eventstore::grpc] Failed to retrieve gossip information from candidate Endpoint { host: "10.43.68.27", port: 31311 }: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
[2022-01-14T13:53:44Z WARN  eventstore::grpc] Unable to select a node. Retrying...(3/3)
[2022-01-14T13:53:44Z ERROR eventstore::grpc] Maximum discovery attempt count reached: 3
[2022-01-14T13:53:44Z DEBUG eventstore::grpc] Current msg: Msg::GetChannel, rest: [[]]
Error: GrpcConnectionError(MaxDiscoveryAttemptReached(3))
```

**Comment by YoEight** [comment]
@cloudgk Can you share your server configuration and your code too, please?
Also please mention which version of the Rust client you are using.

**Comment by YoEight** [comment]
You forgot to post your Rust code.

Could you post the log of the server too, please? I'm having some doubts that the server started properly.

**Comment by GenerallyIntelligent** [comment]
Hey @YoEight. Thanks for helping us out on this issue (And others :smile:).
I have put together the a minimal example for the rust code in this [gist](https://gist.github.com/GenerallyIntelligent/f9926c71fbfdc73ed4a31cb8eacb14d8). There is the `main.rs`, `Cargo.toml` and a console output included. The eventstore client version is `1.0.0`.

@cloudgk should be able to look into the server logs soon.
Thanks again!

**Comment by cloudgk** [comment]
@YoEight Do you want to see the logs of EvenstoreDB service or EvenstoreAdmin? Also the UI is completely up and running.

**Comment by YoEight** [comment]
By looking at the log of the client, it seems to be a configuration issue on how the server is exposed publicly:

```
[2022-01-15T04:45:45Z DEBUG eventstore::grpc] Failed to retrieve gossip information from candidate Endpoint { host: "34.106.8.238", port: 31311 }: status: Unknown, message: "h2 protocol error: connection error detected: frame with invalid size", details: [], metadata: MetadataMap { headers: {} }
```

Starting from version 20.6, clients do a gRPC call to read the gossip request, so in this case are you sure `34.106.8.238:31311` is suitable to serve such a request?

**Comment by cloudgk** [comment]
@YoEight I have tried with the private address too. I could only debug by using telnet if port is accessible on the ip and that port is the node port.

**Comment by YoEight** [comment]
Considering the whole configuration, I would rather start working on a local version first and build from there. It's hard to help you here considering all the variables. As a side note, I strongly advise you to move to the latest alpha version of the Rust client on Crates.io considering the stable release is very soon and the API is not entirely the same.

**Comment by cloudgk** [comment]
@YoEight Okay, thank you

**Comment by YoEight** [comment]
I forgot to mention that if you want to test a cluster configuration locally, give our docker-compose file a try. I use this one to test the Rust client: https://github.com/EventStore/EventStoreDB-Client-Rust/blob/master/docker-compose.yml (we also have a `vars.env` associated with it). Please update the image version accordingly.

**Comment by tqwewe** [comment]
I've tried installing EventStore DB with the docker-compose installation (`image: eventstore/eventstore:21.10.2-buster-slim`).
It seemed to work just fine, and I can connect to the admin dashboard at `localhost:2113`... though trying to connect to it from Rust, I also get `Error: GrpcConnectionError(MaxDiscoveryAttemptReached(3))`.

```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let settings = "esdb://admin:changeit@localhost:1113".parse()?;
    let client = Client::new(settings)?;
    client
        .list_all_persistent_subscriptions(&ListPersistentSubscriptionsOptions::default())
        .await?;
        
    Ok(())
}
```

**Comment by tqwewe** [comment]
I've solved it.
Add `?tls=false` to your connection info.

```rust
let settings = "esdb://admin:changeit@localhost:2113?tls=false".parse()?;
```
